### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by m-dennisgocong** [hannahkim313/rps-game#1]
#### User Story
As a player,  instead of just "Game over!", on the final pop-up. I want to have a "Congratulations you win!",  and "Sorry, you lose!"  if I lose.

####  Description
The final pop-up on displayGameOver() function always display "Game over!" even if I win the game.

**Comment by hannahkim313** [comment]
Thank you for the input, the message now displays whether the player has won or lost the game based on the final score.
